### ISSUE TITLE
Custom Ecnahntment

### ISSUE THREAD

**Issue by Hurming** [aabssmc/Skuishy#11]
```register [a] [new] custom ecnahntment (with name|named) %string%:
    rarity: %enchantRarity%
    classes: %enchantClasses% # basically applicable to
    conflicts with: %customenchantments/enchantments%
    chance per level: %number%
    chance handler: # Section for handeling greater chances
    proc: # section for when it procs```

so I need to do a new custom enchant?
so if u can please add this to Skuishy

**Comment by Fusezion** [comment]
Fancy but not something within bukkit api so you're asking for something fully custom. Not sure how this would apply to this addon since there's more than just one thing needing to be done

**Comment by Hurming** [comment]
> Fancy but not something within bukkit api so you're asking for something fully custom. Not sure how this would apply to this addon since there's more than just one thing needing to be done

Okay, so what should I do now? What I mean is, can you do it in the future or not? Or maybe because I really need it.

**Comment by ghost** [comment]
if bukkit ever adds api i will add it

**Comment by Fusezion** [comment]
For the time being I'm closing this issue, I may return in the future when spigot adds support for custom enchantments or when paper finishes off their holder api which should hopefully lead to future implementations
