### ISSUE TITLE
Server lag

### ISSUE THREAD

**Issue by feeeedox** [aabssmc/Skuishy#5]
After the plugin has been loaded, the server stops loading and after 5 minutes it continues.

MC: 1.20.4
Java: 18

(No, it is not due to the specifications of my server)
![image](https://github.com/aabssmc/Skuishy/assets/67076970/fadb2967-fe64-4b62-b94f-21bbef8f8046)
![image](https://github.com/aabssmc/Skuishy/assets/67076970/5b9967b7-b685-4bcd-a2c2-3f0dddc12f9f)

**Comment by ghost** [comment]
do any errors pop up in console when it loads, or does it just hang? also do you have any other plugins that might conflict with skuishy?

**Comment by feeeedox** [comment]
![image](https://github.com/aabssmc/Skuishy/assets/67076970/ac08d80b-edcb-4e71-a9ea-100f4273edc6)
Well i dont have so much plugins on it. And yeah it just hang.

**Comment by ghost** [comment]
if skolo is a skript addon for decent holograms, it might be conflicting with skuishy since skuishy has the same syntax

**Comment by feeeedox** [comment]
Skolo is a addon from me, i added it cause Skuishy was causing these problems on my side .-.

**Comment by ghost** [comment]
ok i think i figured out why it was happening, it should be fixed in 2.0
