### ISSUE TITLE
[FEATURE] Network Variable with MySQL

### ISSUE THREAD

**Issue by Lennord** [aabssmc/Skuishy#8]
Hello, it would be good to add a network variable system with MySQL (or other database) because all the other addons that do that, it doesn't work very correctly so if you can add this system, I think what would be good for the users.

I know it's complex but I think it would be good for the addon.

**Comment by ghost** [comment]
i have no clue how to use databases lmao

**Comment by Lennord** [comment]
Ah okay it doesn't matter

**Comment by Lennord** [comment]
otherwise do you have the possibility to store the network variables on a bungeecord/velocity?

**Comment by ghost** [comment]
nah idk how to use proxys
ill maybe learn and try to add it

**Comment by Lennord** [comment]
ok take your time to learn, don't worry this addition can wait while you learn how to use proxies. after you can look in the code of other addons that do it to learn in short good learning.
